In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,6,5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

In [4]:
print(a+b)
print(a-b)
print(a*b)

[9 9 9 9 9 9 9 9]
[-7 -5 -3 -1  1  3  5  7]
[ 8 14 18 20 20 18 14  8]


In [5]:
#creating a 2d array
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [6]:
#3d array
a3 = np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
print(a3)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [10]:
print(a2.shape)
print(a3.ndim)
print(a2.dtype)

(2, 2)
3
int64


In [11]:
lst = []
for i in range(1,21):
    lst.append(i)
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [14]:
np.arange(10)
np.arange(2,21)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
np.random.randint(1,11, size=(2,3))

array([[ 8,  7, 10],
       [ 2,  8, 10]], dtype=int32)

In [18]:
x = np.array([[7,2,3],
             [2,5,2],
             [3,5,1]])

y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [19]:
print(x*y)

[[ 7 16  9]
 [ 6 35  4]
 [ 6 25  3]]


In [ ]:
print(x@y) #matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [22]:
np.dot(x,y) #matrix multiplication

array([[19, 85, 34],
       [21, 61, 22],
       [20, 64, 22]])

In [23]:
x.prod() #product of all elements of the array

np.int64(12600)

In [25]:
x.mean() #mean of all elements

np.float64(3.3333333333333335)

In [26]:
y.mean()

np.float64(3.7777777777777777)

In [28]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [ ]:
x.mean(axis = 0) #column wise mean

array([4., 4., 2.])

In [29]:
y.mean(axis = 1) #row wise mean

array([4.        , 4.        , 3.33333333])

In [30]:
print(x.sum())
print(x.std())
print(x.var())

30
1.8257418583505538
3.3333333333333335


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) #1st quartile
print(np.percentile(a,50)) #median
print(np.percentile(a,75)) #3rd quartile

3.0
5.0
7.0


In [34]:
b = np.random.randint(11,100, (4,4))
print(b)

[[84 24 67 38]
 [91 94 41 45]
 [54 94 79 14]
 [97 34 56 27]]


In [38]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[84 24 67 38 91 94 41 45]
 [54 94 79 14 97 34 56 27]]
8X2
[[84 24]
 [67 38]
 [91 94]
 [41 45]
 [54 94]
 [79 14]
 [97 34]
 [56 27]]


In [40]:
x = np.random.randint(1,11 ,(5,5))
print(x)

[[ 8  4  6  1  6]
 [ 1  5  7  9  7]
 [ 5 10  9  2  8]
 [ 3  9  5  4  1]
 [ 8  9  4  9 10]]


In [45]:
print(x[0]) #1st row
print(x[0,1]) #1st row and 2nd column's first element
print(x[-1])

print(x[:3])
print(x[3:])

[8 4 6 1 6]
4
[ 8  9  4  9 10]
[[ 8  4  6  1  6]
 [ 1  5  7  9  7]
 [ 5 10  9  2  8]]
[[ 3  9  5  4  1]
 [ 8  9  4  9 10]]
