In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,6,5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

In [4]:
print(a+b)
print(a-b)
print(a*b)

[9 9 9 9 9 9 9 9]
[-7 -5 -3 -1  1  3  5  7]
[ 8 14 18 20 20 18 14  8]


In [ ]:
#creating a 2d array
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [7]:
#3d array
a3 = np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
print(a3)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]
